version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"  # Для веб-интерфейса
    networks:
      - app_network

  github_service:
    build:
      context: .
      dockerfile: domain/aggregate/github_service/Dockerfile
    env_file:
      - .env
    container_name: github_service
    restart: always
    networks:
      - app_network
    depends_on:
      - rabbitmq

  report_service:
    build:
      context: .
      dockerfile: domain/aggregate/report_service/Dockerfile
    container_name: report_service
    restart: always
    networks:
      - app_network
    depends_on:
      - rabbitmq

  analysis_service:
    build:
      context: .
      dockerfile: models/Dockerfile
    container_name: analysis_service
    restart: always
    networks:
      - app_network
    depends_on:
      - rabbitmq

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    env_file:
      - .env
    container_name: bot
    restart: always
    volumes:
      - ./bot/code_evaluation.db:/app/code_evaluation.db
    networks:
      - app_network
    depends_on:
      - rabbitmq
      - github_service
      - report_service
      - analysis_service

networks:
  app_network:
    driver: bridge
